/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ArticlesCreateRouteImport } from './routes/articles.create'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRagRouteImport } from './routes/admin.rag'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ArticlesIdEditRouteImport } from './routes/articles.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ArticlesCreateRoute = ArticlesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRagRoute = AdminRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticlesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/rag': typeof AdminRagRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/create': typeof ArticlesCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/rag': typeof AdminRagRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/create': typeof ArticlesCreateRoute
  '/admin': typeof AdminIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/rag': typeof AdminRagRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/create': typeof ArticlesCreateRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/login'
    | '/media'
    | '/profile'
    | '/register'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/rag'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/users'
    | '/articles/$id'
    | '/articles/create'
    | '/admin/'
    | '/articles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/login'
    | '/media'
    | '/profile'
    | '/register'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/rag'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/users'
    | '/articles/$id'
    | '/articles/create'
    | '/admin'
    | '/articles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/login'
    | '/media'
    | '/profile'
    | '/register'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/rag'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/users'
    | '/articles/$id'
    | '/articles/create'
    | '/admin/'
    | '/articles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/articles/create': {
      id: '/articles/create'
      path: '/create'
      fullPath: '/articles/create'
      preLoaderRoute: typeof ArticlesCreateRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rag': {
      id: '/admin/rag'
      path: '/rag'
      fullPath: '/admin/rag'
      preLoaderRoute: typeof AdminRagRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/articles/$id/edit': {
      id: '/articles/$id/edit'
      path: '/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof ArticlesIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminRagRoute: typeof AdminRagRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminRagRoute: AdminRagRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesIdRouteChildren {
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
}

const ArticlesIdRouteChildren: ArticlesIdRouteChildren = {
  ArticlesIdEditRoute: ArticlesIdEditRoute,
}

const ArticlesIdRouteWithChildren = ArticlesIdRoute._addFileChildren(
  ArticlesIdRouteChildren,
)

interface ArticlesRouteChildren {
  ArticlesIdRoute: typeof ArticlesIdRouteWithChildren
  ArticlesCreateRoute: typeof ArticlesCreateRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesIdRoute: ArticlesIdRouteWithChildren,
  ArticlesCreateRoute: ArticlesCreateRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
